config/routes.rb
WorkoutApp::Application.routes.draw do

  get "pages/home"

	match '/signup', to: 'users#new'

	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :schedules, only: [:create, :destroy]
	resources :elements, only: [:create, :destroy]

	match '/signin', to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	root :to => "pages#home"

end

app/models/element.rb
class Element < ActiveRecord::Base
  attr_accessible :schedule_id
	validates :schedule_id, presence: true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	has_many :elements, dependent: :destroy

	default_scope order: 'schedules.created_at ASC'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password
	has_secure_password
	has_many :schedules, dependent: :destroy
	before_save :create_remember_token

	validates :name, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }

	def schedule_list
		Schedule.where("user_id = ?", id)
	end

	private

		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	include SessionsHelper
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
	before_filter :signed_in_user, only: [:create, :destroy]

	def create
		@element = current_user.schedules[0].elements.build(params[:element])
		if @element.save
			flash[:success] = "Element added to schedule!"
			redirect_to root_path
		end
	end

	def destroy
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
		if signed_in?
			@schedule = current_user.schedules.build
			@schedule_list_items = current_user.schedule_list
			@element = current_user.schedules[0].elements.build
		end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	before_filter :signed_in_user, only: [:create, :destroy]
	before_filter :correct_user, only: :destroy

	def create
		@schedule = current_user.schedules.build(params[:schedule])
		if @schedule.save
			flash[:success] = "Schedule added!"
			redirect_to root_path
		else
			@schedule_list_items = []
			render 'static_pages/home'
		end
	end

	def destroy
		@schedule.destroy
		redirect_back_or root_path
	end

	private

		def correct_user
			@schedule = current_user.schedules.find_by_id(params[:id])
			redirect_to root_path if @schedule.nil?
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:edit, :update]
	before_filter :correct_user, only: [:edit, :update]

	def show
		@user = User.find(params[:id])
		@schedules = @user.schedules
	end

  def new
		@user = User.new
  end
	
	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to the Sample App!"
			#redirect_to root_path
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile updated"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
	end

	private

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_path) unless current_user?(@user)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Workout App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_path, notice: "Please sign in."
		end
	end

	def sign_out
		current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		clear_return_to
	end

	def store_location
		session[:return_to] = request.fullpath
	end

	private

		def user_from_remember_token
			remember_token = cookies[:remember_token]
			User.find_by_remember_token(remember_token) unless remember_token.nil?
		end

		def clear_return_to
			session.delete(:return_to)
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Workout Randomizer", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Settings", edit_user_path(current_user) %></li>
						<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			</div>
			<%= yield %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/pages/home.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
		</aside>
			<section>
				<%= render 'shared/schedule_list' %>
				<%= render 'shared/schedule_form' %>
			</section>
	</div>
<% else %>
<div class="center hero-unit">
	<h1>Welcome to the Workout Randomizer App!</h1>
  <h3>Try it out!</h3>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

<% end %>
</div>

app/views/schedules/_schedule.html.erb
<td>Day <%= schedule.user_id %></td>
	<% if current_user?(schedule.user) %>
		<%= link_to "delete", schedule, method: :delete,
																	 	confirm: "You sure?",
																		title: "Schedule: " + schedule.id %>
	<% end %>

app/views/shared/_element_form.html.erb
<%= form_for(@element) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.submit "Add Element to Schedule", class: "btn btn-large btn-primary" %>
<% end %>
	

app/views/shared/_element_item.html.erb
<li id="<%= element_item.id %>">
SCHEDULE <%= schedule_item.id %>
<% if current_user?(schedule_item.user) %>
	<%= link_to "delete", schedule_item, method: :delete,
																			 confirm: "You sure?",
																			 title: "Schedule" + schedule_item.id.to_s %>
	<%= render 'shared/element_form' %>
<% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id = "error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_schedule_form.html.erb
<%= form_for(@schedule) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.submit "Add Schedule Item", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_schedule_item.html.erb
<li id="<%= schedule_item.id %>">
SCHEDULE <%= schedule_item.id %>
<% if current_user?(schedule_item.user) %>
	<%= link_to "delete", schedule_item, method: :delete,
																			 confirm: "You sure?",
																			 title: "Schedule" + schedule_item.id.to_s %>
	<%= render 'shared/element_form' %>
<% end %>
</li>

app/views/shared/_schedule_list.html.erb
<% if @schedule_list_items.any? %>
	<h3>Schedule:</h3>
	<%= render partial: 'shared/schedule_item', collection: @schedule_list_items %>
<% else %>
	<h3>Schedule Empty!</h3>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
	<%= current_user.email %>
</h1>
<span>
	<%= link_to "view my profile", current_user %>
</span>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<h2><%= @user.email %></h2>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<h1><%= @user.name %>, <%= @user.email %></h1>
<div class="row">
	<div class="span8">
		<% if @user.schedules.any? %>
			<h3>Schedule</h3>
			<table>
			<tr>
			<% counter = 1 %>
			<%= @schedules.each do |sched, i| %>
				<td>Day <%= counter %></td>
				<% counter+=1 %>
			<% end %>
			</tr>
			</table>
		<% else %>
			<h4>No schedule created yet</h4>
		<% end %>
	</div>
</div>